delete wraped namespace because the error below
Undefined symbols for architecture x86_64:
  "third::func()", referenced from:
      wrappedNamespace() in main.cpp.o
  "third::fourth::func()", referenced from:
      wrappedNamespace() in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)